version: '2'
services:
  auth:
    build:
      context: database
      dockerfile: db_auth.dockerfile
    container_name: auth
    environment:
      MYSQL_ROOT_PASSWORD: 204655
    command: --init-file /auth.sql --bind-address=0.0.0.0
  tokens:
    build:
      context: database
      dockerfile: db_tokens.dockerfile
    container_name: tokens
    environment:
      MYSQL_ROOT_PASSWORD: 204655
    command: --init-file /tokens.sql --bind-address=0.0.0.0
  consul:
    image: consul
    container_name: consul
    command: agent -server -client=0.0.0.0 -bootstrap -node=master -bind=0.0.0.0
    volumes:
      - /mnt:/data
    ports:
      - 8500:8500
      - 8400:8400
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8300:8300
  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    network_mode: host
    hostname: registrator
    command: consul://127.0.0.1:8500
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  service.auth:
    build:
      context: ../
      dockerfile: auth.dockerfile
    container_name: service.auth
    command: ./wait-for-it -t=15 auth:3306 "./yii migrate --migrationPath=@app/migrations/db_auth --db=db_auth --interactive=0 -c && php auth.php"
    environment:
      CONSUL_URI: http://consul:8500
    depends_on:
      - registrator
      - auth
    links:
      - auth
      - consul
    ports:
      - localhost:8888:8888
  service.tokens:
    build:
      context: ../
      dockerfile: tokens.dockerfile
    container_name: service.tokens
    command: ./wait-for-it -t=15 tokens:3306 "./yii migrate --migrationPath=@app/migrations/db_tokens --db=db_tokens --interactive=0 -c && php tokens.php"
    depends_on:
      - registrator
      - tokens
    environment:
        CONSUL_URI: http://consul:8500
    links:
      - tokens
      - consul
    ports:
      - localhost:8889:8888
  gateway:
    build: app
    links:
      - service.tokens
      - service.auth
    ports:
      - 80